---
title: "lab project"
author: "Haocheng Zhang"
date: "12/28/2022"
output: html_document
---


```{r, echo=TRUE}
#import library and dataset
library(readxl)
library(dplyr)
library(imputeTS)
library(quickpsy)
library(ggplot2)
library(pracma)
data = read_excel("/Users/mac/Desktop/23_1_TTCtactile2IFC.mat.xlsx")
data$pickComp=0
data$pickComp = ifelse(data$positionComp==data$response,1,0)
#pick comp as earlier
data_earlier = data[data$pickComp==1,]
data_earlier_grouped = data_earlier %>% group_by(TTCstandard, TTCcomp) %>%
  dplyr::summarise(total_num = n(),.groups = 'drop')
data_grouped = data %>% group_by(TTCstandard, TTCcomp) %>% 
  dplyr::summarise(total_num = n(),.groups = 'drop')
grouped = merge(data_grouped,data_earlier_grouped,by=c("TTCstandard", "TTCcomp"),
                all.x=TRUE)
grouped = na_replace(grouped,0)
grouped$percentage = grouped$total_num.y/grouped$total_num.x
grouped$diff = grouped$TTCcomp-grouped$TTCstandard
colnames(grouped)[3]="numTrials"
colnames(grouped)[4]="pickComp"

#two dataframes for different TTstandard
grouped_1 = grouped[grouped$TTCstandard==0.75,]
grouped_2 = grouped[grouped$TTCstandard==1.5,]
grouped_1$percentage_later = 1-grouped_1$percentage
grouped_2$percentage_later = 1-grouped_2$percentage

#standard=0.75
plot(grouped_1$diff,grouped_1$percentage,type="l",main="TTCstandard=0.75",
     xlab = "TTC Difference (Comparison – Standard)",ylab="P(Comparison Stimulus Earlier)",
     xaxt='n',ylim=c(0,1))
axis(side=1,at=c(-0.45, -0.3, 0,-0.15, 0.15,0.3,0.45))

#standard = 1.5
plot(grouped_2$diff,grouped_2$percentage,type="l",main="TTCstandard=1.5",
     xlab = "TTC Difference (Comparison – Standard)",ylab="P(Comparison Stimulus Earlier)",
     xaxt='n',ylim=c(0,1))
axis(side=1,at=c(-1.2, -0.8, -0.4,0, 0.4,0.8,1.2))
```

```{r, echo=TRUE}
#Fit the Psychometric Curve
#not constrained

fit_psychometric <- function(data,standard){
  fit = quickpsy(grouped_1,diff,pickComp,numTrials)
  pData <- ggplot(grouped_1, aes(x = diff, y = percentage)) + 
           geom_point()
  PSF_result <- pData +
                geom_line(data= fit$curves, aes(x = x, y = y))+
                xlim(-1.5,1.5)+
                ggtitle(paste0("Unconstrained PSF when Standard = ", standard))+
                xlab("TTC Difference (Comparison – Standard)")+
                ylab("P(Comparison Stimulus Earlier)")
  
  #constrained
  p<- ggplot()+
    geom_point(data=data,aes(x=diff,y=percentage))
  Negativie_log_lik <- function(p) { # negative log likelihood
    phi <- pnorm(data$diff, p[1], p[2]) 
    -sum(data$pickComp * log(phi) + (data$numTrials - data$pickComp) * log(1 - phi) )
  }
  para <- optim(c(.7, .7), Negativie_log_lik)$par
  xseq <- seq(-1.5, 1.5, .01)
  yseq <- pnorm(xseq, para[1], para[2])
  curve <- data.frame(xseq, yseq)
  p_final<-p + geom_line(data = curve,aes(x = xseq, y = yseq))+
           ggtitle(paste0("Constrained PSF when Standard = ", standard))+
           xlab("TTC Difference (Comparison – Standard)")+
          ylab("P(Comparison Stimulus Earlier)")
  
  plot(PSF_result)
  plot(p_final)
}

```

```{r, echo=TRUE}
fit_psychometric(grouped_1,0.75)
fit_psychometric(grouped_2,1.5)
```

```{r, echo=TRUE}
grouped_1
grouped_2
```
